/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './ty-progressbar.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from './ty-progressbar.component.css.shim';
export class Wrapper_TyProgressbarComponent {
  context:import0.TyProgressbarComponent;
  changed:boolean;
  constructor() {
    this.changed = false;
    this.context = new import0.TyProgressbarComponent();
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_TyProgressbarComponent_Host:import2.RenderComponentType = (null as any);
class _View_TyProgressbarComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _TyProgressbarComponent_0_4:Wrapper_TyProgressbarComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_TyProgressbarComponent_Host0,renderType_TyProgressbarComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'app-ty-progressbar',import4.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_TyProgressbarComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._TyProgressbarComponent_0_4 = new Wrapper_TyProgressbarComponent();
    this._appEl_0.initComponent(this._TyProgressbarComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._TyProgressbarComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.TyProgressbarComponent) && (0 === requestNodeIndex))) { return this._TyProgressbarComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._TyProgressbarComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._TyProgressbarComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_TyProgressbarComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_TyProgressbarComponent_Host === (null as any))) { (renderType_TyProgressbarComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_TyProgressbarComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const TyProgressbarComponentNgFactory:import9.ComponentFactory<import0.TyProgressbarComponent> = new import9.ComponentFactory<import0.TyProgressbarComponent>('app-ty-progressbar',viewFactory_TyProgressbarComponent_Host0,import0.TyProgressbarComponent);
const styles_TyProgressbarComponent:any[] = [import10.styles];
var renderType_TyProgressbarComponent:import2.RenderComponentType = (null as any);
class _View_TyProgressbarComponent0 extends import1.AppView<import0.TyProgressbarComponent> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_TyProgressbarComponent0,renderType_TyProgressbarComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = import4.createRenderElement(this.renderer,parentRenderNode,'div',new import4.InlineArrayDynamic(32,'animation','false','c_stroke_width','4','canvasHeight','40','canvasWidth','480','circleR','15','circleRX','20','circleRY','20','class','','id','pb','initrectwidth','300','params','{status:1,score:94,apdex:0,errorPercent:1,responseTime:0}','r_stroke_width','2','rectHeight','6','rectWidth','300','showlegend','fasle','style','margin-top:0px;margin-left:50%; margin-right: 136px; position: relative;/*  z-index:101; */'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n',(null as any));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
}
export function viewFactory_TyProgressbarComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.TyProgressbarComponent> {
  if ((renderType_TyProgressbarComponent === (null as any))) { (renderType_TyProgressbarComponent = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.Emulated,styles_TyProgressbarComponent,{})); }
  return new _View_TyProgressbarComponent0(viewUtils,parentInjector,declarationEl);
}