/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['.tyc-footer[_ngcontent-%COMP%]{width:auto;padding:10px 30px 50px;background:#eeeeee;}\r\n.tyc-footer-con[_ngcontent-%COMP%]{height:30px;line-height:30px;text-align:right;}'];