/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './ty-footer.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from './ty-footer.component.css.shim';
export class Wrapper_TyFooterComponent {
  context:import0.TyFooterComponent;
  changed:boolean;
  constructor() {
    this.changed = false;
    this.context = new import0.TyFooterComponent();
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_TyFooterComponent_Host:import2.RenderComponentType = (null as any);
class _View_TyFooterComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _TyFooterComponent_0_4:Wrapper_TyFooterComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_TyFooterComponent_Host0,renderType_TyFooterComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'app-ty-footer',import4.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_TyFooterComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._TyFooterComponent_0_4 = new Wrapper_TyFooterComponent();
    this._appEl_0.initComponent(this._TyFooterComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._TyFooterComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.TyFooterComponent) && (0 === requestNodeIndex))) { return this._TyFooterComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._TyFooterComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._TyFooterComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_TyFooterComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_TyFooterComponent_Host === (null as any))) { (renderType_TyFooterComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_TyFooterComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const TyFooterComponentNgFactory:import9.ComponentFactory<import0.TyFooterComponent> = new import9.ComponentFactory<import0.TyFooterComponent>('app-ty-footer',viewFactory_TyFooterComponent_Host0,import0.TyFooterComponent);
const styles_TyFooterComponent:any[] = [import10.styles];
var renderType_TyFooterComponent:import2.RenderComponentType = (null as any);
class _View_TyFooterComponent0 extends import1.AppView<import0.TyFooterComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_TyFooterComponent0,renderType_TyFooterComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = import4.createRenderElement(this.renderer,parentRenderNode,'div',new import4.InlineArray2(2,'class','tyc-footer'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n		',(null as any));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray2(2,'class','tyc-footer-con'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'© 2007-2016  北京基调网络股份有限公司',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._text_5 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_7 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray2(2,'class','fw-wrap'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n          ',(null as any));
    this._el_9 = import4.createRenderElement(this.renderer,this._el_7,'a',new import4.InlineArray2(2,'href','javascript:NTKF.im_openInPageChat(\'kf_9212_1459247902327\')'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n            ',(null as any));
    this._el_11 = import4.createRenderElement(this.renderer,this._el_9,'span',new import4.InlineArray4(4,'class','fw-txt','style','display: none;'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'在线咨询',(null as any));
    this._text_13 = this.renderer.createText(this._el_9,'\n			',(null as any));
    this._el_14 = import4.createRenderElement(this.renderer,this._el_9,'span',new import4.InlineArray2(2,'class','fw-btn fw-online'),(null as any));
    this._text_15 = this.renderer.createText(this._el_9,'\n            ',(null as any));
    this._el_16 = import4.createRenderElement(this.renderer,this._el_9,'div',new import4.InlineArray2(2,'class','clear'),(null as any));
    this._text_17 = this.renderer.createText(this._el_9,'\n          ',(null as any));
    this._text_18 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._text_19 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._text_20 = this.renderer.createText(this._el_0,'\n ',(null as any));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._text_20
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
}
export function viewFactory_TyFooterComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.TyFooterComponent> {
  if ((renderType_TyFooterComponent === (null as any))) { (renderType_TyFooterComponent = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.Emulated,styles_TyFooterComponent,{})); }
  return new _View_TyFooterComponent0(viewUtils,parentInjector,declarationEl);
}