/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './ty-sidebar.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/common/src/location/location';
import * as import9 from '@angular/router/src/router';
import * as import10 from '../menu.service';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from './ty-sidebar.component.css.shim';
import * as import14 from '../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import15 from '@angular/core/src/linker/template_ref';
import * as import16 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import17 from '@angular/common/src/directives/ng_for';
export class Wrapper_TySidebarComponent {
  context:import0.TySidebarComponent;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this.context = new import0.TySidebarComponent(p0,p1,p2);
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_TySidebarComponent_Host:import2.RenderComponentType = (null as any);
class _View_TySidebarComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _TySidebarComponent_0_4:Wrapper_TySidebarComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_TySidebarComponent_Host0,renderType_TySidebarComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'app-ty-sidebar',import4.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_TySidebarComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._TySidebarComponent_0_4 = new Wrapper_TySidebarComponent(this.parentInjector.get(import8.Location),this.parentInjector.get(import9.Router),this.parentInjector.get(import10.MenuService));
    this._appEl_0.initComponent(this._TySidebarComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._TySidebarComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.TySidebarComponent) && (0 === requestNodeIndex))) { return this._TySidebarComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._TySidebarComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._TySidebarComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_TySidebarComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_TySidebarComponent_Host === (null as any))) { (renderType_TySidebarComponent_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_TySidebarComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const TySidebarComponentNgFactory:import12.ComponentFactory<import0.TySidebarComponent> = new import12.ComponentFactory<import0.TySidebarComponent>('app-ty-sidebar',viewFactory_TySidebarComponent_Host0,import0.TySidebarComponent);
const styles_TySidebarComponent:any[] = [import13.styles];
var renderType_TySidebarComponent:import2.RenderComponentType = (null as any);
class _View_TySidebarComponent0 extends import1.AppView<import0.TySidebarComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _anchor_19:any;
  /*private*/ _appEl_19:import3.AppElement;
  _TemplateRef_19_5:any;
  _NgFor_19_6:import14.Wrapper_NgFor;
  _text_20:any;
  _text_21:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_TySidebarComponent0,renderType_TySidebarComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = import4.createRenderElement(this.renderer,parentRenderNode,'div',new import4.InlineArray8(6,'class','tyc-sidebar ','id','sidebar','style','height: 1076px;'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n		',(null as any));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray4(4,'class','tyc-sidebar-cicon','mini','false'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n			',(null as any));
    this._el_4 = import4.createRenderElement(this.renderer,this._el_2,'div',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n				',(null as any));
    this._el_6 = import4.createRenderElement(this.renderer,this._el_4,'span',new import4.InlineArray2(2,'class','tyc-sidebar-cicon01'),(null as any));
    this._text_7 = this.renderer.createText(this._el_4,'\n				',(null as any));
    this._el_8 = import4.createRenderElement(this.renderer,this._el_4,'span',new import4.InlineArray2(2,'class','tyc-sidebar-cicon02'),(null as any));
    this._text_9 = this.renderer.createText(this._el_4,'\n				',(null as any));
    this._el_10 = import4.createRenderElement(this.renderer,this._el_4,'span',new import4.InlineArray2(2,'class','tyc-sidebar-cicon03'),(null as any));
    this._text_11 = this.renderer.createText(this._el_4,'\n				',(null as any));
    this._el_12 = import4.createRenderElement(this.renderer,this._el_4,'span',new import4.InlineArray2(2,'class','tyc-sidebar-cicon04'),(null as any));
    this._text_13 = this.renderer.createText(this._el_4,'\n			',(null as any));
    this._text_14 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._text_15 = this.renderer.createText(this._el_0,'\n		\n		',(null as any));
    this._el_16 = import4.createRenderElement(this.renderer,this._el_0,'ul',new import4.InlineArray2(2,'class','tyc-sidebar-nav'),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'\n			',(null as any));
    this._text_18 = this.renderer.createText(this._el_16,'\n			',(null as any));
    this._anchor_19 = this.renderer.createTemplateAnchor(this._el_16,(null as any));
    this._appEl_19 = new import3.AppElement(19,16,this,this._anchor_19);
    this._TemplateRef_19_5 = new import15.TemplateRef_(this._appEl_19,viewFactory_TySidebarComponent1);
    this._NgFor_19_6 = new import14.Wrapper_NgFor(this._appEl_19.vcRef,this._TemplateRef_19_5,this.parentInjector.get(import16.IterableDiffers),this.ref);
    this._text_20 = this.renderer.createText(this._el_16,'\n		',(null as any));
    this._text_21 = this.renderer.createText(this._el_0,'\n	   \n      ',(null as any));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._anchor_19,
      this._text_20,
      this._text_21
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.TemplateRef) && (19 === requestNodeIndex))) { return this._TemplateRef_19_5; }
    if (((token === import17.NgFor) && (19 === requestNodeIndex))) { return this._NgFor_19_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_19_0_0:any = this.context.menus;
    this._NgFor_19_6.check_ngForOf(currVal_19_0_0,throwOnChange,false);
    this._NgFor_19_6.detectChangesInInputProps(this,this._anchor_19,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_TySidebarComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.TySidebarComponent> {
  if ((renderType_TySidebarComponent === (null as any))) { (renderType_TySidebarComponent = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.Emulated,styles_TySidebarComponent,{})); }
  return new _View_TySidebarComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_TySidebarComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_TySidebarComponent1,renderType_TySidebarComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.createRenderElement(this.renderer,(null as any),'li',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n				',(null as any));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'a',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'				\n					',(null as any));
    this._el_4 = import4.createRenderElement(this.renderer,this._el_2,'span',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_2,' ',(null as any));
    this._el_6 = import4.createRenderElement(this.renderer,this._el_2,'em',new import4.InlineArray2(2,'class','tyc-siebar-text'),(null as any));
    this._el_7 = import4.createRenderElement(this.renderer,this._el_6,'em',new import4.InlineArray2(2,'class','tyc-sidebar-arrow'),(null as any));
    this._text_8 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n				',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n			',(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._text_10
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_11:any = import4.interpolate(1,'tyc-sidebar-nav-a  ',(this.context.$implicit.active? 'current': ''),'');
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementProperty(this._el_2,'className',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = import4.interpolate(1,'tyc-sidebar-icon ',this.context.$implicit.icon,'');
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementProperty(this._el_4,'className',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = import4.interpolate(1,'',this.context.$implicit.label,'');
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setText(this._text_8,currVal_13);
      this._expr_13 = currVal_13;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_TySidebarComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_TySidebarComponent1(viewUtils,parentInjector,declarationEl);
}