/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './ty-header.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '../menu.service';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/common/src/location/location';
import * as import10 from '@angular/router/src/router';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from './ty-header.component.css.shim';
import * as import14 from '../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import15 from '@angular/core/src/linker/template_ref';
import * as import16 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import17 from '@angular/common/src/directives/ng_for';
import * as import18 from '../../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import19 from '@angular/router/src/router_state';
import * as import20 from '@angular/common/src/location/location_strategy';
import * as import21 from '@angular/router/src/directives/router_link';
export class Wrapper_TyHeaderComponent {
  context:import0.TyHeaderComponent;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this.context = new import0.TyHeaderComponent(p0,p1,p2);
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_TyHeaderComponent_Host:import2.RenderComponentType = (null as any);
class _View_TyHeaderComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _MenuService_0_4:import4.MenuService;
  _TyHeaderComponent_0_5:Wrapper_TyHeaderComponent;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement) {
    super(_View_TyHeaderComponent_Host0,renderType_TyHeaderComponent_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import5.selectOrCreateRenderHostElement(this.renderer,'app-ty-header',import5.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_TyHeaderComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._MenuService_0_4 = new import4.MenuService(this.parentInjector.get(import9.Location),this.parentInjector.get(import10.Router));
    this._TyHeaderComponent_0_5 = new Wrapper_TyHeaderComponent(this.parentInjector.get(import9.Location),this.parentInjector.get(import10.Router),this._MenuService_0_4);
    this._appEl_0.initComponent(this._TyHeaderComponent_0_5.context,([] as any[]),compView_0);
    compView_0.create(this._TyHeaderComponent_0_5.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import4.MenuService) && (0 === requestNodeIndex))) { return this._MenuService_0_4; }
    if (((token === import0.TyHeaderComponent) && (0 === requestNodeIndex))) { return this._TyHeaderComponent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._TyHeaderComponent_0_5.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._TyHeaderComponent_0_5.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_TyHeaderComponent_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_TyHeaderComponent_Host === (null as any))) { (renderType_TyHeaderComponent_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_TyHeaderComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const TyHeaderComponentNgFactory:import12.ComponentFactory<import0.TyHeaderComponent> = new import12.ComponentFactory<import0.TyHeaderComponent>('app-ty-header',viewFactory_TyHeaderComponent_Host0,import0.TyHeaderComponent);
const styles_TyHeaderComponent:any[] = [import13.styles];
var renderType_TyHeaderComponent:import2.RenderComponentType = (null as any);
class _View_TyHeaderComponent0 extends import1.AppView<import0.TyHeaderComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _text_46:any;
  _text_47:any;
  _text_48:any;
  _el_49:any;
  _text_50:any;
  _text_51:any;
  _anchor_52:any;
  /*private*/ _appEl_52:import3.AppElement;
  _TemplateRef_52_5:any;
  _NgFor_52_6:import14.Wrapper_NgFor;
  _text_53:any;
  _text_54:any;
  _el_55:any;
  _text_56:any;
  _el_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _el_61:any;
  _text_62:any;
  _text_63:any;
  _el_64:any;
  _el_65:any;
  _text_66:any;
  _text_67:any;
  _el_68:any;
  _el_69:any;
  _text_70:any;
  _text_71:any;
  _el_72:any;
  _el_73:any;
  _text_74:any;
  _text_75:any;
  _el_76:any;
  _el_77:any;
  _text_78:any;
  _text_79:any;
  _text_80:any;
  _text_81:any;
  _el_82:any;
  _text_83:any;
  _el_84:any;
  _text_85:any;
  _text_86:any;
  _el_87:any;
  _text_88:any;
  _text_89:any;
  _text_90:any;
  _el_91:any;
  _text_92:any;
  _el_93:any;
  _text_94:any;
  _el_95:any;
  _text_96:any;
  _el_97:any;
  _text_98:any;
  _text_99:any;
  _text_100:any;
  _text_101:any;
  _el_102:any;
  _text_103:any;
  _el_104:any;
  _text_105:any;
  _el_106:any;
  _text_107:any;
  _el_108:any;
  _text_109:any;
  _text_110:any;
  _text_111:any;
  _text_112:any;
  _el_113:any;
  _text_114:any;
  _el_115:any;
  _text_116:any;
  _el_117:any;
  _text_118:any;
  _text_119:any;
  _el_120:any;
  _text_121:any;
  _text_122:any;
  _text_123:any;
  _text_124:any;
  _text_125:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement) {
    super(_View_TyHeaderComponent0,renderType_TyHeaderComponent,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'      ',(null as any));
    this._el_1 = import5.createRenderElement(this.renderer,parentRenderNode,'div',new import5.InlineArray2(2,'class','tyc-header clear'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n        ',(null as any));
    this._el_3 = import5.createRenderElement(this.renderer,this._el_1,'a',new import5.InlineArray8(6,'class','tyc-logo float-left','href','http://www.tingyun.com','target','_blank'),(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'\n          ',(null as any));
    this._el_5 = import5.createRenderElement(this.renderer,this._el_3,'img',new import5.InlineArray8(6,'height','30','src','/assets/images/tyc-logo.png','width','82'),(null as any));
    this._text_6 = this.renderer.createText(this._el_3,'\n        ',(null as any));
    this._text_7 = this.renderer.createText(this._el_1,'\n        ',(null as any));
    this._el_8 = import5.createRenderElement(this.renderer,this._el_1,'div',new import5.InlineArray4(4,'class','tyc-pro-cur float-left','id','tyc-pro-cur'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._el_10 = import5.createRenderElement(this.renderer,this._el_8,'a',new import5.InlineArray4(4,'class','tyc-pro-cur-a','href','javascript:void();'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'Server',(null as any));
    this._text_12 = this.renderer.createText(this._el_8,' \n        ',(null as any));
    this._el_13 = import5.createRenderElement(this.renderer,this._el_8,'span',new import5.InlineArray4(4,'class','tyc-pro-arrow','id','tyc-pro-cur-arrow'),(null as any));
    this._text_14 = this.renderer.createText(this._el_1,'\n        ',(null as any));
    this._el_15 = import5.createRenderElement(this.renderer,this._el_1,'ul',new import5.InlineArray8(6,'class','tyc-nav-pro','id','tyc-nav-pro','style','display: none;'),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'\n          ',(null as any));
    this._el_17 = import5.createRenderElement(this.renderer,this._el_15,'li',import5.EMPTY_INLINE_ARRAY,(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'\n            ',(null as any));
    this._el_19 = import5.createRenderElement(this.renderer,this._el_17,'a',new import5.InlineArray4(4,'href','http://localhost:8080/mobile','target','_blank'),(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'App',(null as any));
    this._text_21 = this.renderer.createText(this._el_17,'\n          ',(null as any));
    this._text_22 = this.renderer.createText(this._el_15,'\n          ',(null as any));
    this._el_23 = import5.createRenderElement(this.renderer,this._el_15,'li',import5.EMPTY_INLINE_ARRAY,(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'\n            ',(null as any));
    this._el_25 = import5.createRenderElement(this.renderer,this._el_23,'a',new import5.InlineArray4(4,'class','pro-current','href',''),(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'Server',(null as any));
    this._text_27 = this.renderer.createText(this._el_23,'\n          ',(null as any));
    this._text_28 = this.renderer.createText(this._el_15,'\n          ',(null as any));
    this._el_29 = import5.createRenderElement(this.renderer,this._el_15,'li',import5.EMPTY_INLINE_ARRAY,(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'\n            ',(null as any));
    this._el_31 = import5.createRenderElement(this.renderer,this._el_29,'a',new import5.InlineArray4(4,'href','','target','_blank'),(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'Browser',(null as any));
    this._text_33 = this.renderer.createText(this._el_29,'\n          ',(null as any));
    this._text_34 = this.renderer.createText(this._el_15,'\n          ',(null as any));
    this._text_35 = this.renderer.createText(this._el_15,'\n          ',(null as any));
    this._el_36 = import5.createRenderElement(this.renderer,this._el_15,'li',import5.EMPTY_INLINE_ARRAY,(null as any));
    this._text_37 = this.renderer.createText(this._el_36,'\n            ',(null as any));
    this._el_38 = import5.createRenderElement(this.renderer,this._el_36,'a',new import5.InlineArray4(4,'href','http://localhost:8080/network','target','_blank'),(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'Network',(null as any));
    this._text_40 = this.renderer.createText(this._el_36,'\n          ',(null as any));
    this._text_41 = this.renderer.createText(this._el_15,'\n          ',(null as any));
    this._el_42 = import5.createRenderElement(this.renderer,this._el_15,'li',import5.EMPTY_INLINE_ARRAY,(null as any));
    this._text_43 = this.renderer.createText(this._el_42,'\n            ',(null as any));
    this._el_44 = import5.createRenderElement(this.renderer,this._el_42,'a',new import5.InlineArray4(4,'href','http://localhost:8080/sys','target','_blank'),(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'Sys',(null as any));
    this._text_46 = this.renderer.createText(this._el_42,'\n          ',(null as any));
    this._text_47 = this.renderer.createText(this._el_15,'\n        ',(null as any));
    this._text_48 = this.renderer.createText(this._el_1,'\n		',(null as any));
    this._el_49 = import5.createRenderElement(this.renderer,this._el_1,'ul',new import5.InlineArray2(2,'class','tyc-mainmenu float-left'),(null as any));
    this._text_50 = this.renderer.createText(this._el_49,'\n		',(null as any));
    this._text_51 = this.renderer.createText(this._el_49,'\n		 ',(null as any));
    this._anchor_52 = this.renderer.createTemplateAnchor(this._el_49,(null as any));
    this._appEl_52 = new import3.AppElement(52,49,this,this._anchor_52);
    this._TemplateRef_52_5 = new import15.TemplateRef_(this._appEl_52,viewFactory_TyHeaderComponent1);
    this._NgFor_52_6 = new import14.Wrapper_NgFor(this._appEl_52.vcRef,this._TemplateRef_52_5,this.parentInjector.get(import16.IterableDiffers),this.ref);
    this._text_53 = this.renderer.createText(this._el_49,'\n        ',(null as any));
    this._text_54 = this.renderer.createText(this._el_1,'\n        ',(null as any));
    this._el_55 = import5.createRenderElement(this.renderer,this._el_1,'ul',new import5.InlineArray2(2,'class','tyc-rightmenu float-right'),(null as any));
    this._text_56 = this.renderer.createText(this._el_55,'\n		',(null as any));
    this._el_57 = import5.createRenderElement(this.renderer,this._el_55,'li',new import5.InlineArray2(2,'class','tyc-user'),(null as any));
    this._text_58 = this.renderer.createText(this._el_57,'\n			',(null as any));
    this._el_59 = import5.createRenderElement(this.renderer,this._el_57,'div',new import5.InlineArray2(2,'class','tyc-user-icon'),(null as any));
    this._text_60 = this.renderer.createText(this._el_57,'\n			',(null as any));
    this._el_61 = import5.createRenderElement(this.renderer,this._el_57,'ul',new import5.InlineArray2(2,'class','tyc-user-list'),(null as any));
    this._text_62 = this.renderer.createText(this._el_61,'\n				',(null as any));
    this._text_63 = this.renderer.createText(this._el_61,'				\n				',(null as any));
    this._el_64 = import5.createRenderElement(this.renderer,this._el_61,'li',import5.EMPTY_INLINE_ARRAY,(null as any));
    this._el_65 = import5.createRenderElement(this.renderer,this._el_64,'a',new import5.InlineArray4(4,'href','http://saaslocal.tingyun.com:8080/lens-saas/userService/myproduct','target','_blank'),(null as any));
    this._text_66 = this.renderer.createText(this._el_65,'用户中心',(null as any));
    this._text_67 = this.renderer.createText(this._el_61,'\n				',(null as any));
    this._el_68 = import5.createRenderElement(this.renderer,this._el_61,'li',import5.EMPTY_INLINE_ARRAY,(null as any));
    this._el_69 = import5.createRenderElement(this.renderer,this._el_68,'a',new import5.InlineArray4(4,'href','http://saaslocal.tingyun.com:8080/lens-saas/userCenter/updatePassword','target','_blank'),(null as any));
    this._text_70 = this.renderer.createText(this._el_69,'修改密码',(null as any));
    this._text_71 = this.renderer.createText(this._el_61,'				\n				',(null as any));
    this._el_72 = import5.createRenderElement(this.renderer,this._el_61,'li',import5.EMPTY_INLINE_ARRAY,(null as any));
    this._el_73 = import5.createRenderElement(this.renderer,this._el_72,'a',new import5.InlineArray4(4,'href','/report-server/authKey','target','_blank'),(null as any));
    this._text_74 = this.renderer.createText(this._el_73,'修改授权码',(null as any));
    this._text_75 = this.renderer.createText(this._el_61,'\n				',(null as any));
    this._el_76 = import5.createRenderElement(this.renderer,this._el_61,'li',import5.EMPTY_INLINE_ARRAY,(null as any));
    this._el_77 = import5.createRenderElement(this.renderer,this._el_76,'a',new import5.InlineArray4(4,'href','javascript:void(0);','id','logout_click'),(null as any));
    this._text_78 = this.renderer.createText(this._el_77,'退出',(null as any));
    this._text_79 = this.renderer.createText(this._el_61,'\n			',(null as any));
    this._text_80 = this.renderer.createText(this._el_57,'\n		',(null as any));
    this._text_81 = this.renderer.createText(this._el_55,'\n		',(null as any));
    this._el_82 = import5.createRenderElement(this.renderer,this._el_55,'li',import5.EMPTY_INLINE_ARRAY,(null as any));
    this._text_83 = this.renderer.createText(this._el_82,'	\n				',(null as any));
    this._el_84 = import5.createRenderElement(this.renderer,this._el_82,'div',new import5.InlineArray2(2,'class','tyc-lang'),(null as any));
    this._text_85 = this.renderer.createText(this._el_84,'\n					',(null as any));
    this._text_86 = this.renderer.createText(this._el_84,'\n					',(null as any));
    this._el_87 = import5.createRenderElement(this.renderer,this._el_84,'a',new import5.InlineArray4(4,'class','tyc-icon-cn language','langvalue','_zh'),(null as any));
    this._text_88 = this.renderer.createText(this._el_84,'\n\n				',(null as any));
    this._text_89 = this.renderer.createText(this._el_82,'\n		',(null as any));
    this._text_90 = this.renderer.createText(this._el_55,'\n		',(null as any));
    this._el_91 = import5.createRenderElement(this.renderer,this._el_55,'li',import5.EMPTY_INLINE_ARRAY,(null as any));
    this._text_92 = this.renderer.createText(this._el_91,'\n			',(null as any));
    this._el_93 = import5.createRenderElement(this.renderer,this._el_91,'a',new import5.InlineArray8(6,'class','tyc-rightmenu-a tyc-a-help','href','http://doc.tingyun.com/help/html/doc/server.html','target','_blank'),(null as any));
    this._text_94 = this.renderer.createText(this._el_93,'\n				',(null as any));
    this._el_95 = import5.createRenderElement(this.renderer,this._el_93,'span',new import5.InlineArray2(2,'class','tyc-a-icon tyc-a-icon-help'),(null as any));
    this._text_96 = this.renderer.createText(this._el_93,'\n				',(null as any));
    this._el_97 = import5.createRenderElement(this.renderer,this._el_93,'span',import5.EMPTY_INLINE_ARRAY,(null as any));
    this._text_98 = this.renderer.createText(this._el_97,'帮助',(null as any));
    this._text_99 = this.renderer.createText(this._el_93,'\n			',(null as any));
    this._text_100 = this.renderer.createText(this._el_91,'\n		',(null as any));
    this._text_101 = this.renderer.createText(this._el_55,'\n		',(null as any));
    this._el_102 = import5.createRenderElement(this.renderer,this._el_55,'li',import5.EMPTY_INLINE_ARRAY,(null as any));
    this._text_103 = this.renderer.createText(this._el_102,'\n			',(null as any));
    this._el_104 = import5.createRenderElement(this.renderer,this._el_102,'a',new import5.InlineArray8(6,'class','tyc-rightmenu-a tyc-a-download','href','/download/serverSdk','target','_blank'),(null as any));
    this._text_105 = this.renderer.createText(this._el_104,'\n				',(null as any));
    this._el_106 = import5.createRenderElement(this.renderer,this._el_104,'span',new import5.InlineArray2(2,'class','tyc-a-icon tyc-a-icon-download'),(null as any));
    this._text_107 = this.renderer.createText(this._el_104,'\n				',(null as any));
    this._el_108 = import5.createRenderElement(this.renderer,this._el_104,'span',import5.EMPTY_INLINE_ARRAY,(null as any));
    this._text_109 = this.renderer.createText(this._el_108,'探针下载',(null as any));
    this._text_110 = this.renderer.createText(this._el_104,'\n			',(null as any));
    this._text_111 = this.renderer.createText(this._el_102,'\n		',(null as any));
    this._text_112 = this.renderer.createText(this._el_55,'\n		',(null as any));
    this._el_113 = import5.createRenderElement(this.renderer,this._el_55,'li',import5.EMPTY_INLINE_ARRAY,(null as any));
    this._text_114 = this.renderer.createText(this._el_113,'\n			',(null as any));
    this._el_115 = import5.createRenderElement(this.renderer,this._el_113,'a',new import5.InlineArray8(6,'class','tyc-rightmenu-a tyc-a-alarm','href','http://reportlocal.tingyun.com/tingyun-report-alarm/alarm/list','target','_blank'),(null as any));
    this._text_116 = this.renderer.createText(this._el_115,'\n					',(null as any));
    this._el_117 = import5.createRenderElement(this.renderer,this._el_115,'span',new import5.InlineArray2(2,'class','tyc-a-icon tyc-a-icon-alarm'),(null as any));
    this._text_118 = this.renderer.createText(this._el_117,'						\n					',(null as any));
    this._text_119 = this.renderer.createText(this._el_115,'\n				',(null as any));
    this._el_120 = import5.createRenderElement(this.renderer,this._el_115,'span',import5.EMPTY_INLINE_ARRAY,(null as any));
    this._text_121 = this.renderer.createText(this._el_120,'告警',(null as any));
    this._text_122 = this.renderer.createText(this._el_115,'\n			',(null as any));
    this._text_123 = this.renderer.createText(this._el_113,'\n		',(null as any));
    this._text_124 = this.renderer.createText(this._el_55,'\n	',(null as any));
    this._text_125 = this.renderer.createText(this._el_1,'\n      ',(null as any));
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._text_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._text_51,
      this._anchor_52,
      this._text_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._text_63,
      this._el_64,
      this._el_65,
      this._text_66,
      this._text_67,
      this._el_68,
      this._el_69,
      this._text_70,
      this._text_71,
      this._el_72,
      this._el_73,
      this._text_74,
      this._text_75,
      this._el_76,
      this._el_77,
      this._text_78,
      this._text_79,
      this._text_80,
      this._text_81,
      this._el_82,
      this._text_83,
      this._el_84,
      this._text_85,
      this._text_86,
      this._el_87,
      this._text_88,
      this._text_89,
      this._text_90,
      this._el_91,
      this._text_92,
      this._el_93,
      this._text_94,
      this._el_95,
      this._text_96,
      this._el_97,
      this._text_98,
      this._text_99,
      this._text_100,
      this._text_101,
      this._el_102,
      this._text_103,
      this._el_104,
      this._text_105,
      this._el_106,
      this._text_107,
      this._el_108,
      this._text_109,
      this._text_110,
      this._text_111,
      this._text_112,
      this._el_113,
      this._text_114,
      this._el_115,
      this._text_116,
      this._el_117,
      this._text_118,
      this._text_119,
      this._el_120,
      this._text_121,
      this._text_122,
      this._text_123,
      this._text_124,
      this._text_125
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.TemplateRef) && (52 === requestNodeIndex))) { return this._TemplateRef_52_5; }
    if (((token === import17.NgFor) && (52 === requestNodeIndex))) { return this._NgFor_52_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_52_0_0:any = this.context.menus;
    this._NgFor_52_6.check_ngForOf(currVal_52_0_0,throwOnChange,false);
    this._NgFor_52_6.detectChangesInInputProps(this,this._anchor_52,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_TyHeaderComponent0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement):import1.AppView<import0.TyHeaderComponent> {
  if ((renderType_TyHeaderComponent === (null as any))) { (renderType_TyHeaderComponent = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.Emulated,styles_TyHeaderComponent,{})); }
  return new _View_TyHeaderComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_TyHeaderComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _RouterLinkWithHref_2_3:import18.Wrapper_RouterLinkWithHref;
  _text_3:any;
  _text_4:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement) {
    super(_View_TyHeaderComponent1,renderType_TyHeaderComponent,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
    this._expr_6 = import8.UNINITIALIZED;
    this._expr_7 = import8.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import5.createRenderElement(this.renderer,(null as any),'li',import5.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n			',(null as any));
    this._el_2 = import5.createRenderElement(this.renderer,this._el_0,'a',new import5.InlineArray2(2,'style','cursor:pointer'),(null as any));
    this._RouterLinkWithHref_2_3 = new import18.Wrapper_RouterLinkWithHref(this.parent.parentInjector.get(import10.Router),this.parent.parentInjector.get(import19.ActivatedRoute),this.parent.parentInjector.get(import20.LocationStrategy));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n		 ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import21.RouterLinkWithHref) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._RouterLinkWithHref_2_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = import5.interpolate(1,'',this.context.$implicit.uri,'');
    this._RouterLinkWithHref_2_3.check_routerLink(currVal_2_0_0,throwOnChange,false);
    this._RouterLinkWithHref_2_3.detectChangesInInputProps(this,this._el_2,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_6:any = import5.interpolate(2,'',this.context.$implicit.icon,' ',(this.context.$implicit.active? 'current': ''),'');
    if (import5.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementProperty(this._el_2,'className',currVal_6);
      this._expr_6 = currVal_6;
    }
    this._RouterLinkWithHref_2_3.detectChangesInHostProps(this,this._el_2,throwOnChange);
    const currVal_7:any = import5.interpolate(1,'',this.context.$implicit.label,' ');
    if (import5.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setText(this._text_3,currVal_7);
      this._expr_7 = currVal_7;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_2_3.context.ngOnDestroy();
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_2_0:any = ((<any>this._RouterLinkWithHref_2_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_2_0);
  }
}
function viewFactory_TyHeaderComponent1(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_TyHeaderComponent1(viewUtils,parentInjector,declarationEl);
}