/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from './app.component.css.shim';
import * as import11 from './menu.service';
import * as import12 from './ty-header/ty-header.component.ngfactory';
import * as import13 from './ty-sidebar/ty-sidebar.component.ngfactory';
import * as import14 from '../../node_modules/@angular/router/src/directives/router_outlet.ngfactory';
import * as import15 from './ty-footer/ty-footer.component.ngfactory';
import * as import16 from '@angular/common/src/location/location';
import * as import17 from '@angular/router/src/router';
import * as import18 from '@angular/router/src/router_outlet_map';
import * as import19 from '@angular/core/src/linker/component_factory_resolver';
import * as import20 from './ty-header/ty-header.component';
import * as import21 from './ty-sidebar/ty-sidebar.component';
import * as import22 from '@angular/router/src/directives/router_outlet';
import * as import23 from './ty-footer/ty-footer.component';
export class Wrapper_AppComponent {
  context:import0.AppComponent;
  changed:boolean;
  constructor() {
    this.changed = false;
    this.context = new import0.AppComponent();
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_AppComponent_Host:import2.RenderComponentType = (null as any);
class _View_AppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _AppComponent_0_4:Wrapper_AppComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AppComponent_Host0,renderType_AppComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'app-root',import4.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_AppComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._AppComponent_0_4 = new Wrapper_AppComponent();
    this._appEl_0.initComponent(this._AppComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._AppComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AppComponent) && (0 === requestNodeIndex))) { return this._AppComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AppComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._AppComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_AppComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_AppComponent_Host === (null as any))) { (renderType_AppComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_AppComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const AppComponentNgFactory:import9.ComponentFactory<import0.AppComponent> = new import9.ComponentFactory<import0.AppComponent>('app-root',viewFactory_AppComponent_Host0,import0.AppComponent);
const styles_AppComponent:any[] = [import10.styles];
var renderType_AppComponent:import2.RenderComponentType = (null as any);
class _View_AppComponent0 extends import1.AppView<import0.AppComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import3.AppElement;
  _MenuService_3_4:import11.MenuService;
  _TyHeaderComponent_3_5:import12.Wrapper_TyHeaderComponent;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  /*private*/ _appEl_7:import3.AppElement;
  _TySidebarComponent_7_4:import13.Wrapper_TySidebarComponent;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  /*private*/ _appEl_13:import3.AppElement;
  _RouterOutlet_13_5:import14.Wrapper_RouterOutlet;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  /*private*/ _appEl_20:import3.AppElement;
  _TyFooterComponent_20_4:import15.Wrapper_TyFooterComponent;
  _text_21:any;
  _text_22:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AppComponent0,renderType_AppComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'  ',(null as any));
    this._el_1 = import4.createRenderElement(this.renderer,parentRenderNode,'div',new import4.InlineArray2(2,'class','container'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n	',(null as any));
    this._el_3 = import4.createRenderElement(this.renderer,this._el_1,'app-ty-header',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._appEl_3 = new import3.AppElement(3,1,this,this._el_3);
    var compView_3:any = import12.viewFactory_TyHeaderComponent0(this.viewUtils,this.injector(3),this._appEl_3);
    this._MenuService_3_4 = new import11.MenuService(this.parentInjector.get(import16.Location),this.parentInjector.get(import17.Router));
    this._TyHeaderComponent_3_5 = new import12.Wrapper_TyHeaderComponent(this.parentInjector.get(import16.Location),this.parentInjector.get(import17.Router),this._MenuService_3_4);
    this._appEl_3.initComponent(this._TyHeaderComponent_3_5.context,([] as any[]),compView_3);
    compView_3.create(this._TyHeaderComponent_3_5.context,([] as any[]),(null as any));
    this._text_4 = this.renderer.createText(this._el_1,'\n	',(null as any));
    this._el_5 = import4.createRenderElement(this.renderer,this._el_1,'div',new import4.InlineArray2(2,'class','bodyq tyc-container clear'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._el_7 = import4.createRenderElement(this.renderer,this._el_5,'app-ty-sidebar',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._appEl_7 = new import3.AppElement(7,5,this,this._el_7);
    var compView_7:any = import13.viewFactory_TySidebarComponent0(this.viewUtils,this.injector(7),this._appEl_7);
    this._TySidebarComponent_7_4 = new import13.Wrapper_TySidebarComponent(this.parentInjector.get(import16.Location),this.parentInjector.get(import17.Router),this.parentInjector.get(import11.MenuService));
    this._appEl_7.initComponent(this._TySidebarComponent_7_4.context,([] as any[]),compView_7);
    compView_7.create(this._TySidebarComponent_7_4.context,([] as any[]),(null as any));
    this._text_8 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._el_9 = import4.createRenderElement(this.renderer,this._el_5,'div',new import4.InlineArray2(2,'class','tyc-main '),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n				',(null as any));
    this._el_11 = import4.createRenderElement(this.renderer,this._el_9,'div',new import4.InlineArray2(2,'class','tyc-main-content'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'\n                ',(null as any));
    this._el_13 = import4.createRenderElement(this.renderer,this._el_11,'router-outlet',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._appEl_13 = new import3.AppElement(13,11,this,this._el_13);
    this._RouterOutlet_13_5 = new import14.Wrapper_RouterOutlet(this.parentInjector.get(import18.RouterOutletMap),this._appEl_13.vcRef,this.parentInjector.get(import19.ComponentFactoryResolver),(null as any));
    this._text_14 = this.renderer.createText(this._el_11,'\n				',(null as any));
    this._text_15 = this.renderer.createText(this._el_9,'\n            ',(null as any));
    this._text_16 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._el_17 = import4.createRenderElement(this.renderer,this._el_5,'div',new import4.InlineArray2(2,'style','clear: both;'),(null as any));
    this._text_18 = this.renderer.createText(this._el_5,'\n     ',(null as any));
    this._text_19 = this.renderer.createText(this._el_1,'\n     ',(null as any));
    this._el_20 = import4.createRenderElement(this.renderer,this._el_1,'app-ty-footer',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._appEl_20 = new import3.AppElement(20,1,this,this._el_20);
    var compView_20:any = import15.viewFactory_TyFooterComponent0(this.viewUtils,this.injector(20),this._appEl_20);
    this._TyFooterComponent_20_4 = new import15.Wrapper_TyFooterComponent();
    this._appEl_20.initComponent(this._TyFooterComponent_20_4.context,([] as any[]),compView_20);
    compView_20.create(this._TyFooterComponent_20_4.context,([] as any[]),(null as any));
    this._text_21 = this.renderer.createText(this._el_1,'\n  ',(null as any));
    this._text_22 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.MenuService) && (3 === requestNodeIndex))) { return this._MenuService_3_4; }
    if (((token === import20.TyHeaderComponent) && (3 === requestNodeIndex))) { return this._TyHeaderComponent_3_5.context; }
    if (((token === import21.TySidebarComponent) && (7 === requestNodeIndex))) { return this._TySidebarComponent_7_4.context; }
    if (((token === import22.RouterOutlet) && (13 === requestNodeIndex))) { return this._RouterOutlet_13_5.context; }
    if (((token === import23.TyFooterComponent) && (20 === requestNodeIndex))) { return this._TyFooterComponent_20_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._TyHeaderComponent_3_5.detectChangesInInputProps(this,this._el_3,throwOnChange);
    this._TySidebarComponent_7_4.detectChangesInInputProps(this,this._el_7,throwOnChange);
    this._RouterOutlet_13_5.detectChangesInInputProps(this,this._el_13,throwOnChange);
    this._TyFooterComponent_20_4.detectChangesInInputProps(this,this._el_20,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._TyHeaderComponent_3_5.detectChangesInHostProps(this,this._el_3,throwOnChange);
    this._TySidebarComponent_7_4.detectChangesInHostProps(this,this._el_7,throwOnChange);
    this._RouterOutlet_13_5.detectChangesInHostProps(this,this._el_13,throwOnChange);
    this._TyFooterComponent_20_4.detectChangesInHostProps(this,this._el_20,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterOutlet_13_5.context.ngOnDestroy();
  }
}
export function viewFactory_AppComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.AppComponent> {
  if ((renderType_AppComponent === (null as any))) { (renderType_AppComponent = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.Emulated,styles_AppComponent,{})); }
  return new _View_AppComponent0(viewUtils,parentInjector,declarationEl);
}