/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['.tyc-container[_ngcontent-%COMP%]{padding:30px 0;background: #eeeeee;}\r\n.bodyq[_ngcontent-%COMP%]{min-width:1200px; width:expression((document.documentElement.clientWidth||document.body.clientWidth)<1200?\'1200px\':\'100%\');}\r\n.clear[_ngcontent-%COMP%]{clear: both;}\r\n.tyc-main[_ngcontent-%COMP%]{width:auto;margin:0 30px 0 150px;}\r\n.tyc-main-min[_ngcontent-%COMP%]{width:auto;margin:0 30px 0 85px;}\r\n\r\n.tyc-main-content[_ngcontent-%COMP%] {\r\n    padding: 12px 25px 0px 20px;\r\n    width: auto;\r\n    border-radius: 5px;\r\n    background: #ffffff;\r\n    min-height:800px;\r\n}\r\n\r\n.tyc-main-header[_ngcontent-%COMP%]{height:50px;padding-top:10px;box-sizing:border-box;-webkit-box-sizing:border-box;border-radius:5px;background:#ffffff;box-shadow:0 0 8px 1px #c0c0c0;margin-bottom:30px;}'];