/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './lazy.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/router/src/router_module';
import * as import4 from '@angular/common/src/localization';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from './lazy.component.ngfactory';
import * as import7 from './lazypage/lazypage.component.ngfactory';
import * as import8 from './lazy.component';
import * as import9 from './lazypage/lazypage.component';
import * as import10 from '@angular/core/src/i18n/tokens';
import * as import11 from '@angular/router/src/router_config_loader';
class LazyModuleInjector extends import0.NgModuleInjector<import1.LazyModule> {
  _CommonModule_0:import2.CommonModule;
  _RouterModule_1:import3.RouterModule;
  _LazyModule_2:import1.LazyModule;
  __LOCALE_ID_3:any;
  __NgLocalization_4:import4.NgLocaleLocalization;
  __ROUTES_5:any[];
  __TRANSLATIONS_FORMAT_6:any;
  constructor(parent:import5.Injector) {
    super(parent,[
      import6.LazyComponentNgFactory,
      import7.LazypageComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _LOCALE_ID_3():any {
    if ((this.__LOCALE_ID_3 == (null as any))) { (this.__LOCALE_ID_3 = 'fr'); }
    return this.__LOCALE_ID_3;
  }
  get _NgLocalization_4():import4.NgLocaleLocalization {
    if ((this.__NgLocalization_4 == (null as any))) { (this.__NgLocalization_4 = new import4.NgLocaleLocalization(this._LOCALE_ID_3)); }
    return this.__NgLocalization_4;
  }
  get _ROUTES_5():any[] {
        if ((this.__ROUTES_5 == (null as any))) { (this.__ROUTES_5 = [[{
          path: '',
          component: import8.LazyComponent,
            children: [{
              path: 'overview',
              component: import9.LazypageComponent
            }
          ]
        }
    ]]); }
    return this.__ROUTES_5;
  }
  get _TRANSLATIONS_FORMAT_6():any {
    if ((this.__TRANSLATIONS_FORMAT_6 == (null as any))) { (this.__TRANSLATIONS_FORMAT_6 = 'xlf'); }
    return this.__TRANSLATIONS_FORMAT_6;
  }
  createInternal():import1.LazyModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._RouterModule_1 = new import3.RouterModule(this.parent.get(import3.ROUTER_FORROOT_GUARD,(null as any)));
    this._LazyModule_2 = new import1.LazyModule();
    return this._LazyModule_2;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.RouterModule)) { return this._RouterModule_1; }
    if ((token === import1.LazyModule)) { return this._LazyModule_2; }
    if ((token === import10.LOCALE_ID)) { return this._LOCALE_ID_3; }
    if ((token === import4.NgLocalization)) { return this._NgLocalization_4; }
    if ((token === import11.ROUTES)) { return this._ROUTES_5; }
    if ((token === import10.TRANSLATIONS_FORMAT)) { return this._TRANSLATIONS_FORMAT_6; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const LazyModuleNgFactory:import0.NgModuleFactory<import1.LazyModule> = new import0.NgModuleFactory(LazyModuleInjector,import1.LazyModule);