/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './home.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from './home.component.css.shim';
import * as import11 from '../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import12 from '../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import13 from '@angular/common/src/pipes/lowercase_pipe';
import * as import14 from '@angular/core/src/linker/template_ref';
import * as import15 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import16 from '@angular/common/src/directives/ng_for';
import * as import17 from '@angular/common/src/directives/ng_if';
import * as import18 from '../ty-progressbar/ty-progressbar.component.ngfactory';
import * as import19 from '../ty-progressbar/ty-progressbar.component';
import * as import20 from '@angular/core/src/security';
export class Wrapper_HomeComponent {
  context:import0.HomeComponent;
  changed:boolean;
  constructor() {
    this.changed = false;
    this.context = new import0.HomeComponent();
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_HomeComponent_Host:import2.RenderComponentType = (null as any);
class _View_HomeComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _HomeComponent_0_4:Wrapper_HomeComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_HomeComponent_Host0,renderType_HomeComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'app-home',import4.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_HomeComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HomeComponent_0_4 = new Wrapper_HomeComponent();
    this._appEl_0.initComponent(this._HomeComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._HomeComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.HomeComponent) && (0 === requestNodeIndex))) { return this._HomeComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._HomeComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._HomeComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_HomeComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_HomeComponent_Host === (null as any))) { (renderType_HomeComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_HomeComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const HomeComponentNgFactory:import9.ComponentFactory<import0.HomeComponent> = new import9.ComponentFactory<import0.HomeComponent>('app-home',viewFactory_HomeComponent_Host0,import0.HomeComponent);
const styles_HomeComponent:any[] = [
  '.changeUrl_position[_ngcontent-%COMP%] {\n                        width: 200px;margin-top: 2px;\n                        }',
  import10.styles
]
;
var renderType_HomeComponent:import2.RenderComponentType = (null as any);
class _View_HomeComponent0 extends import1.AppView<import0.HomeComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  _text_51:any;
  _el_52:any;
  _text_53:any;
  _el_54:any;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _text_58:any;
  _text_59:any;
  _text_60:any;
  _el_61:any;
  _text_62:any;
  _el_63:any;
  _text_64:any;
  _el_65:any;
  _text_66:any;
  _text_67:any;
  _text_68:any;
  _text_69:any;
  _el_70:any;
  _text_71:any;
  _el_72:any;
  _text_73:any;
  _el_74:any;
  _text_75:any;
  _text_76:any;
  _text_77:any;
  _text_78:any;
  _el_79:any;
  _text_80:any;
  _el_81:any;
  _text_82:any;
  _el_83:any;
  _text_84:any;
  _text_85:any;
  _text_86:any;
  _text_87:any;
  _text_88:any;
  _text_89:any;
  _el_90:any;
  _text_91:any;
  _text_92:any;
  _text_93:any;
  _text_94:any;
  _anchor_95:any;
  /*private*/ _appEl_95:import3.AppElement;
  _TemplateRef_95_5:any;
  _NgFor_95_6:import11.Wrapper_NgFor;
  _text_96:any;
  _text_97:any;
  _el_98:any;
  _text_99:any;
  _anchor_100:any;
  /*private*/ _appEl_100:import3.AppElement;
  _TemplateRef_100_5:any;
  _NgIf_100_6:import12.Wrapper_NgIf;
  _text_101:any;
  _el_102:any;
  _text_103:any;
  _el_104:any;
  _text_105:any;
  _text_106:any;
  _text_107:any;
  _text_108:any;
  _text_109:any;
  _el_110:any;
  _text_111:any;
  _el_112:any;
  _text_113:any;
  _el_114:any;
  _text_115:any;
  _text_116:any;
  _text_117:any;
  _el_118:any;
  _text_119:any;
  _el_120:any;
  _text_121:any;
  _el_122:any;
  _text_123:any;
  _text_124:any;
  _text_125:any;
  _text_126:any;
  _text_127:any;
  _text_128:any;
  _el_129:any;
  _text_130:any;
  _text_131:any;
  _pipe_lowercase_0:import13.LowerCasePipe;
  /*private*/ _expr_139:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_HomeComponent0,renderType_HomeComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_139 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n\n    ',(null as any));
    this._el_1 = import4.createRenderElement(this.renderer,parentRenderNode,'div',new import4.InlineArray4(4,'class','rum_page_container rum-page-doc','id','appOverview'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n        ',(null as any));
    this._el_3 = import4.createRenderElement(this.renderer,this._el_1,'div',new import4.InlineArray2(2,'style','position:relative'),(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'\n            ',(null as any));
    this._text_5 = this.renderer.createText(this._el_3,'\n        ',(null as any));
    this._text_6 = this.renderer.createText(this._el_1,'\n        ',(null as any));
    this._el_7 = import4.createRenderElement(this.renderer,this._el_1,'div',new import4.InlineArray4(4,'class','rum-page','page_no','1'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._el_9 = import4.createRenderElement(this.renderer,this._el_7,'div',new import4.InlineArray2(2,'class','title_mobile_w_new'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n                ',(null as any));
    this._el_11 = import4.createRenderElement(this.renderer,this._el_9,'div',new import4.InlineArray2(2,'class','title_report_server'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'应用列表(最近30分钟)',(null as any));
    this._text_13 = this.renderer.createText(this._el_9,'\n                ',(null as any));
    this._el_14 = import4.createRenderElement(this.renderer,this._el_9,'div',new import4.InlineArray2(2,'class','float_right'),(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'\n                    ',(null as any));
    this._text_16 = this.renderer.createText(this._el_14,'\n                    ',(null as any));
    this._text_17 = this.renderer.createText(this._el_14,'\n                    ',(null as any));
    this._el_18 = import4.createRenderElement(this.renderer,this._el_14,'span',new import4.InlineArray4(4,'class','tab_content_font4','style','width: 15px;'),(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'\n                    ',(null as any));
    this._text_20 = this.renderer.createText(this._el_14,'\n                    ',(null as any));
    this._el_21 = import4.createRenderElement(this.renderer,this._el_14,'div',new import4.InlineArray4(4,'class','btn_add01','id','open'),(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'新建应用',(null as any));
    this._text_23 = this.renderer.createText(this._el_14,'\n                ',(null as any));
    this._text_24 = this.renderer.createText(this._el_9,'\n            ',(null as any));
    this._text_25 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._el_26 = import4.createRenderElement(this.renderer,this._el_7,'div',new import4.InlineArray4(4,'id','appStatList','url','/report-server/overview/newAppListPage'),(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'\n                \n                ',(null as any));
    this._el_28 = import4.createRenderElement(this.renderer,this._el_26,'div',new import4.InlineArray2(2,'class','rightbox'),(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'\n                    ',(null as any));
    this._el_30 = import4.createRenderElement(this.renderer,this._el_28,'table',new import4.InlineArray16(14,'border','0','cellpadding','0','cellspacing','0','class','forTip table_01 m_top10 tablesorter tablesorter-metro-light','id','applicationList','role','grid','width','100%'),(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'\n                        ',(null as any));
    this._el_32 = import4.createRenderElement(this.renderer,this._el_30,'colgroup',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_33 = this.renderer.createText(this._el_30,'\n                        ',(null as any));
    this._el_34 = import4.createRenderElement(this.renderer,this._el_30,'thead',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_35 = this.renderer.createText(this._el_34,'\n                            ',(null as any));
    this._el_36 = import4.createRenderElement(this.renderer,this._el_34,'tr',new import4.InlineArray4(4,'class','tablesorter-headerRow','role','row'),(null as any));
    this._text_37 = this.renderer.createText(this._el_36,'\n                                ',(null as any));
    this._el_38 = import4.createRenderElement(this.renderer,this._el_36,'th',new import4.InlineArrayDynamic(18,'aria-disabled','true','aria-sort','none','class','alarmStatus sorter-false tablesorter-header  tablesorter-headerUnSorted','data-column','0','role','columnheader','scope','col','style','width: 55%; -webkit-user-select: none;','tabindex','0','unselectable','on'),(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'\n                                    ',(null as any));
    this._el_40 = import4.createRenderElement(this.renderer,this._el_38,'div',new import4.InlineArray2(2,'class','tablesorter-header-inner'),(null as any));
    this._text_41 = this.renderer.createText(this._el_38,'\n                                ',(null as any));
    this._text_42 = this.renderer.createText(this._el_36,'\n                                ',(null as any));
    this._el_43 = import4.createRenderElement(this.renderer,this._el_36,'th',new import4.InlineArrayDynamic(22,'aria-controls','applicationList','aria-disabled','false','aria-label',' 响应时间(ms) : No sort applied, activate to apply an ascending sort','aria-sort','none','class','td_textalgin_r tablesorter-header ','data-column','1','role','columnheader','scope','col','style','width: 13%; -webkit-user-select: none;','tabindex','0','unselectable','on'),(null as any));
    this._text_44 = this.renderer.createText(this._el_43,'\n                                    ',(null as any));
    this._el_45 = import4.createRenderElement(this.renderer,this._el_43,'div',new import4.InlineArray2(2,'class','tablesorter-header-inner'),(null as any));
    this._text_46 = this.renderer.createText(this._el_45,'\n                                        ',(null as any));
    this._el_47 = import4.createRenderElement(this.renderer,this._el_45,'span',new import4.InlineArray4(4,'class','basedonTip','title','应用服务器从收到请求到返回响应的时间'),(null as any));
    this._text_48 = this.renderer.createText(this._el_47,'响应时间(ms)',(null as any));
    this._text_49 = this.renderer.createText(this._el_45,'\n                                    ',(null as any));
    this._text_50 = this.renderer.createText(this._el_43,'\n                                ',(null as any));
    this._text_51 = this.renderer.createText(this._el_36,'\n                                ',(null as any));
    this._el_52 = import4.createRenderElement(this.renderer,this._el_36,'th',new import4.InlineArrayDynamic(22,'aria-controls','applicationList','aria-disabled','false','aria-label',' Apdex : No sort applied, activate to apply an ascending sort','aria-sort','none','class','td_textalgin_r tablesorter-header ','data-column','2','role','columnheader','scope','col','style','width: 7%; -webkit-user-select: none;','tabindex','0','unselectable','on'),(null as any));
    this._text_53 = this.renderer.createText(this._el_52,'\n                                    ',(null as any));
    this._el_54 = import4.createRenderElement(this.renderer,this._el_52,'div',new import4.InlineArray2(2,'class','tablesorter-header-inner'),(null as any));
    this._text_55 = this.renderer.createText(this._el_54,'\n                                        ',(null as any));
    this._el_56 = import4.createRenderElement(this.renderer,this._el_54,'span',new import4.InlineArray4(4,'class','basedonTip','title','Apdex\'>'),(null as any));
    this._text_57 = this.renderer.createText(this._el_56,'Apdex',(null as any));
    this._text_58 = this.renderer.createText(this._el_54,'\n                                    ',(null as any));
    this._text_59 = this.renderer.createText(this._el_52,'\n                                ',(null as any));
    this._text_60 = this.renderer.createText(this._el_36,'\n                                ',(null as any));
    this._el_61 = import4.createRenderElement(this.renderer,this._el_36,'th',new import4.InlineArrayDynamic(22,'aria-controls','applicationList','aria-disabled','false','aria-label',' 错误率(%) : No sort applied, activate to apply an ascending sort','aria-sort','none','class','td_textalgin_r tablesorter-header ','data-column','3','role','columnheader','scope','col','style','width: 9%; -webkit-user-select: none;','tabindex','0','unselectable','on'),(null as any));
    this._text_62 = this.renderer.createText(this._el_61,'\n                                    ',(null as any));
    this._el_63 = import4.createRenderElement(this.renderer,this._el_61,'div',new import4.InlineArray2(2,'class','tablesorter-header-inner'),(null as any));
    this._text_64 = this.renderer.createText(this._el_63,'\n                                        ',(null as any));
    this._el_65 = import4.createRenderElement(this.renderer,this._el_63,'span',new import4.InlineArray4(4,'class','basedonTip','title','应用过程的错误率，指该应用过程在应用服务器端每分钟发生的错误或异常数量占总请求数量的百分比'),(null as any));
    this._text_66 = this.renderer.createText(this._el_65,'\n                                            错误率(%)',(null as any));
    this._text_67 = this.renderer.createText(this._el_63,'\n                                    ',(null as any));
    this._text_68 = this.renderer.createText(this._el_61,'\n                                ',(null as any));
    this._text_69 = this.renderer.createText(this._el_36,'\n                                ',(null as any));
    this._el_70 = import4.createRenderElement(this.renderer,this._el_36,'th',new import4.InlineArrayDynamic(22,'aria-controls','applicationList','aria-disabled','false','aria-label',' 吞吐率(rpm) : No sort applied, activate to apply an ascending sort','aria-sort','none','class','td_textalgin_r tablesorter-header ','data-column','4','role','columnheader','scope','col','style','width: 10%; -webkit-user-select: none;','tabindex','0','unselectable','on'),(null as any));
    this._text_71 = this.renderer.createText(this._el_70,'\n                                    ',(null as any));
    this._el_72 = import4.createRenderElement(this.renderer,this._el_70,'div',new import4.InlineArray2(2,'class','tablesorter-header-inner'),(null as any));
    this._text_73 = this.renderer.createText(this._el_72,'\n                                        ',(null as any));
    this._el_74 = import4.createRenderElement(this.renderer,this._el_72,'span',new import4.InlineArray4(4,'class','basedonTip','title','每分钟接收请求的数量'),(null as any));
    this._text_75 = this.renderer.createText(this._el_74,'吞吐率(rpm)',(null as any));
    this._text_76 = this.renderer.createText(this._el_72,'\n                                    ',(null as any));
    this._text_77 = this.renderer.createText(this._el_70,'\n                                ',(null as any));
    this._text_78 = this.renderer.createText(this._el_36,'\n                                ',(null as any));
    this._el_79 = import4.createRenderElement(this.renderer,this._el_36,'th',new import4.InlineArrayDynamic(18,'aria-disabled','true','aria-sort','none','class','sorter-false td_textalgin_c tablesorter-header tablesorter-headerUnSorted','data-column','5','role','columnheader','scope','col','style','width: 6%; -webkit-user-select: none;','tabindex','0','unselectable','on'),(null as any));
    this._text_80 = this.renderer.createText(this._el_79,'\n                                    ',(null as any));
    this._el_81 = import4.createRenderElement(this.renderer,this._el_79,'div',new import4.InlineArray2(2,'class','tablesorter-header-inner'),(null as any));
    this._text_82 = this.renderer.createText(this._el_81,'\n                                        ',(null as any));
    this._el_83 = import4.createRenderElement(this.renderer,this._el_81,'div',new import4.InlineArray2(2,'style','text-align: right'),(null as any));
    this._text_84 = this.renderer.createText(this._el_83,'操作',(null as any));
    this._text_85 = this.renderer.createText(this._el_81,'\n                                    ',(null as any));
    this._text_86 = this.renderer.createText(this._el_79,'\n                                ',(null as any));
    this._text_87 = this.renderer.createText(this._el_36,'\n                            ',(null as any));
    this._text_88 = this.renderer.createText(this._el_34,'\n                        ',(null as any));
    this._text_89 = this.renderer.createText(this._el_30,'\n                        ',(null as any));
    this._el_90 = import4.createRenderElement(this.renderer,this._el_30,'tbody',new import4.InlineArray8(6,'aria-live','polite','aria-relevant','all','id','hasDataTbody'),(null as any));
    this._text_91 = this.renderer.createText(this._el_90,'\n                            ',(null as any));
    this._text_92 = this.renderer.createText(this._el_90,'\n                            ',(null as any));
    this._text_93 = this.renderer.createText(this._el_90,'\n                        ',(null as any));
    this._text_94 = this.renderer.createText(this._el_30,'\n                        ',(null as any));
    this._anchor_95 = this.renderer.createTemplateAnchor(this._el_30,(null as any));
    this._appEl_95 = new import3.AppElement(95,30,this,this._anchor_95);
    this._TemplateRef_95_5 = new import14.TemplateRef_(this._appEl_95,viewFactory_HomeComponent1);
    this._NgFor_95_6 = new import11.Wrapper_NgFor(this._appEl_95.vcRef,this._TemplateRef_95_5,this.parentInjector.get(import15.IterableDiffers),this.ref);
    this._text_96 = this.renderer.createText(this._el_30,'\n                    ',(null as any));
    this._text_97 = this.renderer.createText(this._el_28,'\n                    ',(null as any));
    this._el_98 = import4.createRenderElement(this.renderer,this._el_28,'div',new import4.InlineArray4(4,'class','showfongt_w','style','display: block;'),(null as any));
    this._text_99 = this.renderer.createText(this._el_98,'\n                        注：将24小时内无数据的应用隐藏。\n                        ',(null as any));
    this._anchor_100 = this.renderer.createTemplateAnchor(this._el_98,(null as any));
    this._appEl_100 = new import3.AppElement(100,98,this,this._anchor_100);
    this._TemplateRef_100_5 = new import14.TemplateRef_(this._appEl_100,viewFactory_HomeComponent3);
    this._NgIf_100_6 = new import12.Wrapper_NgIf(this._appEl_100.vcRef,this._TemplateRef_100_5);
    this._text_101 = this.renderer.createText(this._el_98,'\n                        ',(null as any));
    this._el_102 = import4.createRenderElement(this.renderer,this._el_98,'a',new import4.InlineArray2(2,'id','showHide'),(null as any));
    this._text_103 = this.renderer.createText(this._el_102,'\n                            显示\n                            ',(null as any));
    this._el_104 = import4.createRenderElement(this.renderer,this._el_102,'b',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_105 = this.renderer.createText(this._el_104,'',(null as any));
    this._text_106 = this.renderer.createText(this._el_102,'\n                            个隐藏的应用\n                        ',(null as any));
    this._text_107 = this.renderer.createText(this._el_98,'\n                    ',(null as any));
    this._text_108 = this.renderer.createText(this._el_28,'\n\n\n                ',(null as any));
    this._text_109 = this.renderer.createText(this._el_26,'\n                ',(null as any));
    this._el_110 = import4.createRenderElement(this.renderer,this._el_26,'div',new import4.InlineArray8(6,'class','tooltip2','id','statTooltip','style','margin: 20px; float: left; display: none; position: absolute;'),(null as any));
    this._text_111 = this.renderer.createText(this._el_110,'\n                    ',(null as any));
    this._el_112 = import4.createRenderElement(this.renderer,this._el_110,'div',new import4.InlineArray2(2,'class','icon_arrow'),(null as any));
    this._text_113 = this.renderer.createText(this._el_110,'\n                    ',(null as any));
    this._el_114 = import4.createRenderElement(this.renderer,this._el_110,'div',new import4.InlineArray4(4,'id','tooltipContent','style','float: left;'),(null as any));
    this._text_115 = this.renderer.createText(this._el_114,'正常',(null as any));
    this._text_116 = this.renderer.createText(this._el_110,'\n                ',(null as any));
    this._text_117 = this.renderer.createText(this._el_26,'\n                ',(null as any));
    this._el_118 = import4.createRenderElement(this.renderer,this._el_26,'div',new import4.InlineArray8(6,'class','tooltip2','id','nameTooltip','style','margin: 20px; float: left; display: none; position: absolute;'),(null as any));
    this._text_119 = this.renderer.createText(this._el_118,'\n                    ',(null as any));
    this._el_120 = import4.createRenderElement(this.renderer,this._el_118,'div',new import4.InlineArray2(2,'class','icon_arrow'),(null as any));
    this._text_121 = this.renderer.createText(this._el_118,'\n                    ',(null as any));
    this._el_122 = import4.createRenderElement(this.renderer,this._el_118,'div',new import4.InlineArray4(4,'id','nameTooltip_content','style','float: left;'),(null as any));
    this._text_123 = this.renderer.createText(this._el_122,'正常',(null as any));
    this._text_124 = this.renderer.createText(this._el_118,'\n                ',(null as any));
    this._text_125 = this.renderer.createText(this._el_26,'\n                ',(null as any));
    this._text_126 = this.renderer.createText(this._el_26,'\n            ',(null as any));
    this._text_127 = this.renderer.createText(this._el_7,'\n\n        ',(null as any));
    this._text_128 = this.renderer.createText(this._el_1,'\n        ',(null as any));
    this._el_129 = import4.createRenderElement(this.renderer,this._el_1,'div',new import4.InlineArray2(2,'style','clear: both;'),(null as any));
    this._text_130 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._text_131 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_21,'click',this.eventHandler(this._handle_click_21_0.bind(this)));
    this._pipe_lowercase_0 = new import13.LowerCasePipe();
    var disposable_1:Function = this.renderer.listen(this._el_102,'click',this.eventHandler(this._handle_click_102_0.bind(this)));
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._text_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._text_58,
      this._text_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._text_67,
      this._text_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._el_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._text_76,
      this._text_77,
      this._text_78,
      this._el_79,
      this._text_80,
      this._el_81,
      this._text_82,
      this._el_83,
      this._text_84,
      this._text_85,
      this._text_86,
      this._text_87,
      this._text_88,
      this._text_89,
      this._el_90,
      this._text_91,
      this._text_92,
      this._text_93,
      this._text_94,
      this._anchor_95,
      this._text_96,
      this._text_97,
      this._el_98,
      this._text_99,
      this._anchor_100,
      this._text_101,
      this._el_102,
      this._text_103,
      this._el_104,
      this._text_105,
      this._text_106,
      this._text_107,
      this._text_108,
      this._text_109,
      this._el_110,
      this._text_111,
      this._el_112,
      this._text_113,
      this._el_114,
      this._text_115,
      this._text_116,
      this._text_117,
      this._el_118,
      this._text_119,
      this._el_120,
      this._text_121,
      this._el_122,
      this._text_123,
      this._text_124,
      this._text_125,
      this._text_126,
      this._text_127,
      this._text_128,
      this._el_129,
      this._text_130,
      this._text_131
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.TemplateRef) && (95 === requestNodeIndex))) { return this._TemplateRef_95_5; }
    if (((token === import16.NgFor) && (95 === requestNodeIndex))) { return this._NgFor_95_6.context; }
    if (((token === import14.TemplateRef) && (100 === requestNodeIndex))) { return this._TemplateRef_100_5; }
    if (((token === import17.NgIf) && (100 === requestNodeIndex))) { return this._NgIf_100_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_95_0_0:any = this.context.v_apps;
    this._NgFor_95_6.check_ngForOf(currVal_95_0_0,throwOnChange,false);
    this._NgFor_95_6.detectChangesInInputProps(this,this._anchor_95,throwOnChange);
    const currVal_100_0_0:any = this.context.isExpanded;
    this._NgIf_100_6.check_ngIf(currVal_100_0_0,throwOnChange,false);
    this._NgIf_100_6.detectChangesInInputProps(this,this._anchor_100,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_139:any = import4.interpolate(1,'',this.context.appsum,'');
    if (import4.checkBinding(throwOnChange,this._expr_139,currVal_139)) {
      this.renderer.setText(this._text_105,currVal_139);
      this._expr_139 = currVal_139;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_21_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_21_0:any = ((<any>this.context.installNew()) !== false);
    return (true && pd_21_0);
  }
  private _handle_click_102_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_102_0:any = ((<any>this.context.toggleBody()) !== false);
    return (true && pd_102_0);
  }
}
export function viewFactory_HomeComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.HomeComponent> {
  if ((renderType_HomeComponent === (null as any))) { (renderType_HomeComponent = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.Emulated,styles_HomeComponent,{})); }
  return new _View_HomeComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_HomeComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  /*private*/ _appEl_28:import3.AppElement;
  _TyProgressbarComponent_28_4:import18.Wrapper_TyProgressbarComponent;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _anchor_37:any;
  /*private*/ _appEl_37:import3.AppElement;
  _TemplateRef_37_5:any;
  _NgIf_37_6:import12.Wrapper_NgIf;
  _text_38:any;
  /*private*/ _expr_44:any;
  /*private*/ _expr_45:any;
  /*private*/ _expr_46:any;
  /*private*/ _expr_47:any;
  /*private*/ _expr_48:any;
  _pipe_lowercase_0_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_HomeComponent1,renderType_HomeComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_44 = import7.UNINITIALIZED;
    this._expr_45 = import7.UNINITIALIZED;
    this._expr_46 = import7.UNINITIALIZED;
    this._expr_47 = import7.UNINITIALIZED;
    this._expr_48 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.createRenderElement(this.renderer,(null as any),'tbody',new import4.InlineArray4(4,'class','tablesorter-no-sort','id','hasDataTbody'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                            ',(null as any));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'tr',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n                                ',(null as any));
    this._el_4 = import4.createRenderElement(this.renderer,this._el_2,'td',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n                                    ',(null as any));
    this._el_6 = import4.createRenderElement(this.renderer,this._el_4,'div',new import4.InlineArray2(2,'class','overviewTableTD marginT index-application-list'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n                                        ',(null as any));
    this._el_8 = import4.createRenderElement(this.renderer,this._el_6,'span',new import4.InlineArray4(4,'id','doMore0','idx','0'),(null as any));
    this._text_9 = this.renderer.createText(this._el_6,'\n                                        ',(null as any));
    this._el_10 = import4.createRenderElement(this.renderer,this._el_6,'span',new import4.InlineArray2(2,'class','fenlei_title title'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n                                            ',(null as any));
    this._el_12 = import4.createRenderElement(this.renderer,this._el_10,'a',new import4.InlineArray2(2,'class','strong'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'\n                                                ',(null as any));
    this._el_14 = import4.createRenderElement(this.renderer,this._el_12,'div',new import4.InlineArray8(6,'status','JAVA应用，运行在0个主机上（0个实例）','style','display: inline-block;','type','appNameTooltip'),(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'\n                                                    ',(null as any));
    this._el_16 = import4.createRenderElement(this.renderer,this._el_14,'span',new import4.InlineArray2(2,'class','fenlei_title title'),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'\n                                                        ',(null as any));
    this._el_18 = import4.createRenderElement(this.renderer,this._el_16,'span',new import4.InlineArray2(2,'class','fenlei_title title'),(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'',(null as any));
    this._text_20 = this.renderer.createText(this._el_16,'\n                                                    ',(null as any));
    this._text_21 = this.renderer.createText(this._el_14,'\n                                                ',(null as any));
    this._text_22 = this.renderer.createText(this._el_12,'\n                                            ',(null as any));
    this._text_23 = this.renderer.createText(this._el_10,'\n                                        ',(null as any));
    this._text_24 = this.renderer.createText(this._el_6,'\n                                        ',(null as any));
    this._text_25 = this.renderer.createText(this._el_6,'\n                                            ',(null as any));
    this._el_26 = import4.createRenderElement(this.renderer,this._el_6,'span',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_27 = this.renderer.createText(this._el_6,'\n\n                                       \n											',(null as any));
    this._el_28 = import4.createRenderElement(this.renderer,this._el_6,'app-ty-progressbar',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._appEl_28 = new import3.AppElement(28,6,this,this._el_28);
    var compView_28:any = import18.viewFactory_TyProgressbarComponent0(this.viewUtils,this.injector(28),this._appEl_28);
    this._TyProgressbarComponent_28_4 = new import18.Wrapper_TyProgressbarComponent();
    this._appEl_28.initComponent(this._TyProgressbarComponent_28_4.context,([] as any[]),compView_28);
    compView_28.create(this._TyProgressbarComponent_28_4.context,([] as any[]),(null as any));
    this._text_29 = this.renderer.createText(this._el_6,'\n\n                                    ',(null as any));
    this._text_30 = this.renderer.createText(this._el_4,'\n                                ',(null as any));
    this._text_31 = this.renderer.createText(this._el_2,'\n                                ',(null as any));
    this._text_32 = this.renderer.createText(this._el_2,'\n\n                                ',(null as any));
    this._text_33 = this.renderer.createText(this._el_2,'\n\n                                ',(null as any));
    this._text_34 = this.renderer.createText(this._el_2,'\n                            ',(null as any));
    this._text_35 = this.renderer.createText(this._el_0,'\n                            ',(null as any));
    this._text_36 = this.renderer.createText(this._el_0,'\n\n                            ',(null as any));
    this._anchor_37 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_37 = new import3.AppElement(37,0,this,this._anchor_37);
    this._TemplateRef_37_5 = new import14.TemplateRef_(this._appEl_37,viewFactory_HomeComponent2);
    this._NgIf_37_6 = new import12.Wrapper_NgIf(this._appEl_37.vcRef,this._TemplateRef_37_5);
    this._text_38 = this.renderer.createText(this._el_0,'\n\n                        ',(null as any));
    this._pipe_lowercase_0_0 = import4.pureProxy1((<_View_HomeComponent0>this.parent)._pipe_lowercase_0.transform.bind((<_View_HomeComponent0>this.parent)._pipe_lowercase_0));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._anchor_37,
      this._text_38
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.TyProgressbarComponent) && (28 === requestNodeIndex))) { return this._TyProgressbarComponent_28_4.context; }
    if (((token === import14.TemplateRef) && (37 === requestNodeIndex))) { return this._TemplateRef_37_5; }
    if (((token === import17.NgIf) && (37 === requestNodeIndex))) { return this._NgIf_37_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    this._TyProgressbarComponent_28_4.detectChangesInInputProps(this,this._el_28,throwOnChange);
    const currVal_37_0_0:any = this.context.$implicit.responseTimeTotal;
    this._NgIf_37_6.check_ngIf(currVal_37_0_0,throwOnChange,false);
    this._NgIf_37_6.detectChangesInInputProps(this,this._anchor_37,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_44:any = import4.interpolate(1,'',(this.context.$implicit.hasDataInLast24Hour? 'hasData': 'toggle1'),' ');
    if (import4.checkBinding(throwOnChange,this._expr_44,currVal_44)) {
      this.renderer.setElementProperty(this._el_2,'className',currVal_44);
      this._expr_44 = currVal_44;
    }
    const currVal_45:any = import4.interpolate(1,'',(this.context.$implicit.responseTimeTotal? 'fenlei_add': 'fenlei_no_add'),' domore fenlei_minus_current ');
    if (import4.checkBinding(throwOnChange,this._expr_45,currVal_45)) {
      this.renderer.setElementProperty(this._el_8,'className',currVal_45);
      this._expr_45 = currVal_45;
    }
    const currVal_46:any = import4.interpolate(1,'/report-server/application/',this.context.$implicit.id,'/overview');
    if (import4.checkBinding(throwOnChange,this._expr_46,currVal_46)) {
      this.renderer.setElementProperty(this._el_12,'href',this.viewUtils.sanitizer.sanitize(import20.SecurityContext.URL,currVal_46));
      this._expr_46 = currVal_46;
    }
    const currVal_47:any = import4.interpolate(1,'',this.context.$implicit.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_47,currVal_47)) {
      this.renderer.setText(this._text_19,currVal_47);
      this._expr_47 = currVal_47;
    }
    valUnwrapper.reset();
    const currVal_48:any = import4.interpolate(1,'icon icon-',valUnwrapper.unwrap(import4.castByValue(this._pipe_lowercase_0_0,(<_View_HomeComponent0>this.parent)._pipe_lowercase_0.transform)(this.context.$implicit.language)),'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_48,currVal_48))) {
      this.renderer.setElementProperty(this._el_26,'className',currVal_48);
      this._expr_48 = currVal_48;
    }
    this._TyProgressbarComponent_28_4.detectChangesInHostProps(this,this._el_28,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_HomeComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_HomeComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_HomeComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  /*private*/ _expr_18:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_HomeComponent2,renderType_HomeComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_18 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.createRenderElement(this.renderer,(null as any),'tr',new import4.InlineArray2(2,'class','append'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                                ',(null as any));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'td',new import4.InlineArray2(2,'colspan','6'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n                                    ',(null as any));
    this._el_4 = import4.createRenderElement(this.renderer,this._el_2,'table',new import4.InlineArray8(6,'height','200px','style','border: 1px solid #eee;','width','100%'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n                                        ',(null as any));
    this._el_6 = import4.createRenderElement(this.renderer,this._el_4,'tbody',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n                                            ',(null as any));
    this._el_8 = import4.createRenderElement(this.renderer,this._el_6,'tr',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n                                                ',(null as any));
    this._el_10 = import4.createRenderElement(this.renderer,this._el_8,'td',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n                                                    ',(null as any));
    this._text_12 = this.renderer.createText(this._el_10,'\n                                                ',(null as any));
    this._text_13 = this.renderer.createText(this._el_8,'\n                                            ',(null as any));
    this._text_14 = this.renderer.createText(this._el_6,'\n                                        ',(null as any));
    this._text_15 = this.renderer.createText(this._el_4,'\n                                    ',(null as any));
    this._text_16 = this.renderer.createText(this._el_2,'\n\n                                ',(null as any));
    this._text_17 = this.renderer.createText(this._el_0,'\n                            ',(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._text_17
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_18:any = import4.interpolate(1,'display: ',(this.parent.context.$implicit.isExpanded? ' ': 'none'),'');
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementProperty(this._el_0,'style',this.viewUtils.sanitizer.sanitize(import20.SecurityContext.STYLE,currVal_18));
      this._expr_18 = currVal_18;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_HomeComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_HomeComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_HomeComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_HomeComponent3,renderType_HomeComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.createRenderElement(this.renderer,(null as any),'a',new import4.InlineArray4(4,'herf','','id','showHide'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'隐藏',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0_0:any = ((<any>this.parent.context.toggleBody()) !== false);
    return (true && pd_0_0);
  }
}
function viewFactory_HomeComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_HomeComponent3(viewUtils,parentInjector,declarationEl);
}